sudo: false

language: node_js
node_js:
- '0.11'

cache:
  directories:
  - node_modules

before_install:
- openssl aes-256-cbc -K $encrypted_8c222350cbad_key -iv $encrypted_8c222350cbad_iv
  -in .travis/hlrdesk-staging-dokku.enc -out ~/.ssh/hlrdesk-staging-dokku -d
- psql -c 'CREATE DATABASE travis;' -U postgres

after_success:
- npm run compile-sass
- if [[ "$TRAVIS_BRANCH" == "staging" ]]; then npm run stage; fi

deploy: # see after_success for deployment to staging and master
- provider: heroku
  skip_cleanup: true
  on:
    branch: master
  run: restart
  api_key:
    secure: V8ZQaJ1KiJzu9lVbaX13WCN63uUimznnv71nybAmjXmbIZ/Tn9F6TMBk5R3Psm9AlKHSCFPloFhW6jDmyoBJiBWVVlxUmffGH1kwXjVKcOTTu/3lZJUH1xjSQabQS+OQ8uRBjcDZj/KG3K+YZhck16gsh3/2DzIDN1hJpyPQBKw=
