language: node_js
node_js:
- '0.11'

before_install:
- psql -c 'CREATE DATABASE travis;' -U postgres

after_success:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  openssl aes-256-cbc -K $encrypted_8c222350cbad_key -iv $encrypted_8c222350cbad_iv
  -in .travis/hlrdesk-dokku.enc -out ~/.ssh/hlrdesk-dokku -d; fi

- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ];
  then npm run deploy dev; fi

- if [ "$TRAVIS_BRANCH" == "staging" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ];
  then npm run deploy staging; fi

addons:
  ssh_known_hosts:
  - hlrdesk.byu.edu
  - hlrdesk.hlrdev.byu.edu
  - ianh.hlrdev.byu.edu
  - hlrdesk-staging.byu.edu
